#!/bin/bash

case $1 in

	start)
		killall notify-osd &> /dev/null
		notify-send "Wifi-Manager started"
		$(connection-monitor &> /dev/null & disown)
		;;

	stop)
		killall wifi-monitor &> /dev/null
		killall notify-osd &> /dev/null
		sudo netctl stop-all &> /dev/null
		notify-send "Wifi-Manager stopped"
		;;

	*)
		echo "Usage: wifi-manager [start | stop]"
		;;

esac
