#!/bin/bash

## ip doesn't need sudo to get the current config.
## ip reports ipv4 addresses in the form 'inet ' and
## ipv6 addresses in the form 'inet6 ', hence the space
## in the string comparison. And error message containing
## RTNETLINK informs me that the device is disabled
## at the hardware level

## uses my autoconnect script

if [[ "$(ping -c 1 google.com 2>&1)" == *"failure"* ]]; then
	if [[ "$(sudo ip link set wlp7s0 up 2>&1)" != *"RTNETLINK answers"* ]]; then
		autoconnect
		exit $?
	else
		exit 3
	fi
fi
exit 0
